// Code generated by MockGen. DO NOT EDIT.
// Source: rabbitmqkit.go
//
// Generated by this command:
//
//	mockgen -package=huma -source=rabbitmqkit.go -destination=mock.go
//

// Package huma is a generated GoMock package.
package huma

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockRabbitMQKit is a mock of RabbitMQKit interface.
type MockRabbitMQKit struct {
	ctrl     *gomock.Controller
	recorder *MockRabbitMQKitMockRecorder
	isgomock struct{}
}

// MockRabbitMQKitMockRecorder is the mock recorder for MockRabbitMQKit.
type MockRabbitMQKitMockRecorder struct {
	mock *MockRabbitMQKit
}

// NewMockRabbitMQKit creates a new mock instance.
func NewMockRabbitMQKit(ctrl *gomock.Controller) *MockRabbitMQKit {
	mock := &MockRabbitMQKit{ctrl: ctrl}
	mock.recorder = &MockRabbitMQKitMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRabbitMQKit) EXPECT() *MockRabbitMQKitMockRecorder {
	return m.recorder
}

// BatchPublish mocks base method.
func (m *MockRabbitMQKit) BatchPublish(ctx context.Context, exchange, routingKey string, messages []*Message) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchPublish", ctx, exchange, routingKey, messages)
	ret0, _ := ret[0].(error)
	return ret0
}

// BatchPublish indicates an expected call of BatchPublish.
func (mr *MockRabbitMQKitMockRecorder) BatchPublish(ctx, exchange, routingKey, messages any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchPublish", reflect.TypeOf((*MockRabbitMQKit)(nil).BatchPublish), ctx, exchange, routingKey, messages)
}

// DeclareQueues mocks base method.
func (m *MockRabbitMQKit) DeclareQueues(ctx context.Context, queues ...QueueConfig) error {
	m.ctrl.T.Helper()
	varargs := []any{ctx}
	for _, a := range queues {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DeclareQueues", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeclareQueues indicates an expected call of DeclareQueues.
func (mr *MockRabbitMQKitMockRecorder) DeclareQueues(ctx any, queues ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx}, queues...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeclareQueues", reflect.TypeOf((*MockRabbitMQKit)(nil).DeclareQueues), varargs...)
}

// Publish mocks base method.
func (m *MockRabbitMQKit) Publish(ctx context.Context, exchange, routingKey string, msg *Message) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Publish", ctx, exchange, routingKey, msg)
	ret0, _ := ret[0].(error)
	return ret0
}

// Publish indicates an expected call of Publish.
func (mr *MockRabbitMQKitMockRecorder) Publish(ctx, exchange, routingKey, msg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Publish", reflect.TypeOf((*MockRabbitMQKit)(nil).Publish), ctx, exchange, routingKey, msg)
}

// PublishWithDelayDLXTTL mocks base method.
func (m *MockRabbitMQKit) PublishWithDelayDLXTTL(ctx context.Context, queueName string, msg *Message) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishWithDelayDLXTTL", ctx, queueName, msg)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishWithDelayDLXTTL indicates an expected call of PublishWithDelayDLXTTL.
func (mr *MockRabbitMQKitMockRecorder) PublishWithDelayDLXTTL(ctx, queueName, msg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishWithDelayDLXTTL", reflect.TypeOf((*MockRabbitMQKit)(nil).PublishWithDelayDLXTTL), ctx, queueName, msg)
}

// SetLogger mocks base method.
func (m *MockRabbitMQKit) SetLogger(logger Logger) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetLogger", logger)
}

// SetLogger indicates an expected call of SetLogger.
func (mr *MockRabbitMQKitMockRecorder) SetLogger(logger any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetLogger", reflect.TypeOf((*MockRabbitMQKit)(nil).SetLogger), logger)
}

// SetQos mocks base method.
func (m *MockRabbitMQKit) SetQos(ctx context.Context, prefetchCount, prefetchSize int, global bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetQos", ctx, prefetchCount, prefetchSize, global)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetQos indicates an expected call of SetQos.
func (mr *MockRabbitMQKitMockRecorder) SetQos(ctx, prefetchCount, prefetchSize, global any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetQos", reflect.TypeOf((*MockRabbitMQKit)(nil).SetQos), ctx, prefetchCount, prefetchSize, global)
}

// Shutdown mocks base method.
func (m *MockRabbitMQKit) Shutdown(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Shutdown", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Shutdown indicates an expected call of Shutdown.
func (mr *MockRabbitMQKitMockRecorder) Shutdown(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Shutdown", reflect.TypeOf((*MockRabbitMQKit)(nil).Shutdown), ctx)
}

// Start mocks base method.
func (m *MockRabbitMQKit) Start(ctx context.Context, queues []QueueConfig) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Start", ctx, queues)
	ret0, _ := ret[0].(error)
	return ret0
}

// Start indicates an expected call of Start.
func (mr *MockRabbitMQKitMockRecorder) Start(ctx, queues any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockRabbitMQKit)(nil).Start), ctx, queues)
}
