blank_issues_enabled: false
contact_links:
  - name: Question or discussion
    url: https://github.com/snapp-incubator/huma/discussions
    about: For usage questions and general discussion, please use Discussions instead of opening an issue.
